### ISSUE TITLE
Disorienting startup if no positioning data available

### ISSUE THREAD

**Issue by Thaodan** [otsaloma/poor-maps#15]
Gui is weird when running on FP2.

Ask if I can help to fix this.
![screen](https://cloud.githubusercontent.com/assets/1747359/15799805/54493cb4-2a69-11e6-9235-a26fcf0739ce.png)

**Comment by otsaloma** [comment]
- Do map tiles load at all? Even a part of the screen? I see two shades of grey in your screenshot -- like one them was map tiles and one blank background?
- What happens if you double-tap on screen? It should center the map to your position and you should see the position icon.
- What happens if you tap the menu button at the bottom left? Does the menu page open?

**Comment by Thaodan** [comment]
- No they don't
- Nothing really hapens (at least nothing that I can see).
- yes it opens.

**Comment by otsaloma** [comment]
OK, if the menu page opens, go to Basemaps and try a different tile source, see if something else would load. Also, check that you have positioning enabled in the general Sailfish preferences.

If those don't help, I'd probably need to see console output. Try something like

``` bash
sailfish-qml harbour-poor-maps > poor-maps.log 2>> poor-maps.log
```

at a terminal and copy the log file here.

**Comment by otsaloma** [comment]
Also, see if zooming out works (pinch-zoom) -- do you see a change in the scalebar or do tiles appear? If positioning is off, your map could be centered in some weird place where tiles don't load.

**Comment by Thaodan** [comment]
Zooming, everything of the map is now visible.

[poor-maps.txt](https://github.com/otsaloma/poor-maps/files/299001/poor-maps.txt)

**Comment by otsaloma** [comment]
OK, then I just need to handle the first startup with no positioning data available better -- basically minimum zoom level centered somewhere around Europe should be good.
