### ISSUE TITLE
Please suppport HSL's new APIs

### ISSUE THREAD

**Issue by tuukka** [otsaloma/poor-maps#19]
Thanks for implementing support for HSL's APIs! We have released new APIs and some of them are now in beta. The old APIs will be discontinued soon - perhaps as soon as in 4 months. The new APIs support new features such as realtime data and citybikes.

Digitransit APIs: http://digitransit.fi/en/developers
Other data and APIs from HSL: http://dev.hsl.fi/

**Comment by otsaloma** [comment]
Yes, this is planned, will do. Likely around October or November.
