### ISSUE TITLE
fonts are too small

### ISSUE THREAD

**Issue by alinelena** [otsaloma/poor-maps#2]
Hi 

using poor maps on two devices and the only issue i see up to now is the size of fonts.

on a big screen you can see in the attached pictures the difference.  attached for comparasion the sailfish image too... 
poormaps big screen device
![poormaps_big](https://cloud.githubusercontent.com/assets/3306823/9832133/b5c617e6-5968-11e5-8899-4fbcdddb75f3.png)

sailfish big screen device
![sailfish_big](https://cloud.githubusercontent.com/assets/3306823/9832136/c0012dc2-5968-11e5-820f-40d89cda210a.png)

also from a phone screen nexus 5.
sailfish
![sailfish_small](https://cloud.githubusercontent.com/assets/3306823/9832179/52e17024-596a-11e5-98ab-895541ec8a8a.png)

poormaps
![poormaps_small](https://cloud.githubusercontent.com/assets/3306823/9832181/5c0d5e60-596a-11e5-9939-884c1f5be752.png)

**Comment by otsaloma** [comment]
Is this with the default basemap "Mapbox Streets"? How does it look if you switch to "Mapbox Streets @ 2x"? See Basemaps from the main menu, anything with "@ 2x" should be bigger text. If this is indeed the case and @ 2x is sufficient, I might need to reconsider the default. So far I've just tested with the Jolla phone, which is DPI-wise a borderline case.

And regarding tablets and big screens, some layouts might ill suitable for them. I haven't tested those yet. My Jolla tablet will arrive maybe late October, earliest. After that I might make some changes.

**Comment by alinelena** [comment]
Hi Osmo,

Indeed  I was using the default @2x looks better seems jolla uses even bigger.
Can you offer @4x?

Regards,
Alin

---

Dr Alin Marin Elenahttp://alin.elena.space

---- On Sat, 12 Sep 2015 16:20:11 +0000 Osmo Salomaa&lt;notifications@github.com&gt; wrote ---- 

Is this with the default basemap "Mapbox Streets"? How does it look if you switch to "Mapbox Streets @ 2x"? See Basemaps from the main menu, anything with "@ 2x" should be bigger text. If this is indeed the case and @ 2x is sufficient, I might need to reconsider the default. So far I've just tested with the Jolla phone, which is DPI-wise a borderline case.
 And regarding tablets and big screens, some layouts might ill suitable for them. I haven't tested those yet. My Jolla tablet will arrive maybe late October, earliest. After that I might make some changes.

**Comment by otsaloma** [comment]
Mapbox [doesn't](https://www.mapbox.com/developers/api/maps/#format) offer 4x. Neither do any of the other providers used by Poor. Google does offer 4x and HERE, with a different technical approach, offers four different PPI values, but both of these have unacceptable terms of use.

But setting that default is something I can do, it seems possible in QML using data from [Screen](http://doc.qt.io/qt-5/qml-qtquick-window-screen.html).

**Comment by alinelena** [comment]
Brilliant, thank you!

Alin

---

Dr Alin Marin Elenahttp://alin.elena.space

---- On Sun, 13 Sep 2015 12:46:27 +0000 Osmo Salomaa &lt;notifications@github.com&gt; wrote ---- 

Mapbox doesn't offer 4x. Neither do any of the other providers used by Poor. Google does offer 4x and HERE, with a different technical approach, offers four different PPI values, but both of these have unacceptable terms of use.
 But setting that default is something I can do, it seems possible in QML using data from Screen.

**Comment by otsaloma** [comment]
I chose to simply make 2x the default. When there's 4x tiles available I'll look into the QML Screen thing.
