### ISSUE TITLE
Add route summary

### ISSUE THREAD

**Issue by rinigus** [otsaloma/poor-maps#28]
When calculating a route and using current location as "From", Poor Maps displays total distance and time on the overview of the route on map. This data is missing when shown for routes that are calculated between two addresses. For trip planning, it would be great to get the same overview for routes between addresses.

**Comment by otsaloma** [comment]
The numbers in the top right corner are the distance and time remaining. When calculating a route from the current position, that happens to be the same as the total. When the route is not close to your current position, only the distance is shown and even that is calculated assuming you go straight-line from your current position to the closest route segment and from there along the route to the destination.

But, I agree, the totals would be useful. The right place would probably be the page that lists the maneuvers -- maybe between the Begin, Pause, Clear buttons and the maneuver list?

**Comment by rinigus** [comment]
Good evening!

The totals would fit perfectly on the page with the maneuvers, that's for sure. It would be great addition!

The two numbers displayed on the route map page were a bit of the mystery for me. It was clear that its related to the distance from current location, but not very clear how. Maybe, in addition to having overview in the maneuvers view, its possible to use that overview numbers on the top of the map as well:

Left: distance between current location and the start [straight line]
Right: distance o and time for the route.

But, in the end, it would be great to have  an overview at least somewhere :)

Best wishes,

rinigus

**Comment by otsaloma** [comment]
Looks like this:

![screenshot-20161207-032316](https://cloud.githubusercontent.com/assets/237265/20951418/47f27e24-bc2e-11e6-90f3-c9c72118f9d8.png)

**Comment by rinigus** [comment]
Thank you very much! Looks great!
