### ISSUE TITLE
Saving the POI

### ISSUE THREAD

**Issue by silverhook** [otsaloma/poor-maps#3]
I **really** like your app and prefer it much to the official Jolla Maps.

The biggest issue I have with it is that I cannot save a POI for future use and search for it, like in e.g. the Jolla and Ovi maps.

Let’s say I’m really liked a restaurant or hotel or whatever that I found through Poor Maps and I want to remember it for the next time I’m in that town – I’d like to save that POI and to search/find it when I want to again.

**Comment by otsaloma** [comment]
I have noticed the same, and I agree, being able to save POIs would be useful. But no plans, no ETA, I'm afraid.
