### ISSUE TITLE
Add option for listing-based address search

### ISSUE THREAD

**Issue by bonanza123** [otsaloma/poor-maps#32]
In some cases, where i have e.g. Issues with the spelling of an address or when I'm operating completely offline (via osm scout) a tree- or listing-based address would be helpful. I remember that osmAND has/had something similar, see e.g. http://osmand.net/images/features/search_10.jpg

**Comment by otsaloma** [comment]
Structured search as in that screenshot is not going to happen. I don't find it a good idea in general and it doesn't fit at all in an app that supports multiple different providers, most of which don't support a kind of a query format it would require.

What might help you is search autocompletion, also known as type-ahead search. That is planned, tracked as issue #5.
