### ISSUE TITLE
HTTP requests to local

### ISSUE THREAD

**Issue by rinigus** [otsaloma/poor-maps#37]
While testing Valhalla, I stumbled on an issue with the HTTP requests done by Poor Maps. While I don't know what is an expected request by standard, In particular, its quite different from what browsers, `wget` and `curl` do. As a result, Valhalla's web-engine was not able to parse URL and return routes.

When requesting http://localhost:8002/route?json... by browser (`wget`, `curl`, and simple python program with requests library), valhalla reports

`GET  /route?json=...`

When the same URL is called by Poor Maps, we get

`GET http://127.0.0.1:8002/route?json=...`

I presume that many web-services are able to process it (as well as OSM Scout Server), but "pure" valhalla fails. I think that this behavior is due to  https://github.com/otsaloma/poor-maps/blob/master/poor/http.py#L161 . At this point, you already have connection with the host and still forward full URL. If I parse, remove components 0 and 1 (https://docs.python.org/3/library/urllib.parse.html urllib.parse.urlparse), unparse it back to URL, I get a local URL that works fine with the services that I tested with.

Since I don't know whether the standards allow such GET requests, I am not sure its a bug. But, maybe Poor Maps requests should still be adjusted to be similar to the others.

**Comment by otsaloma** [comment]
By my reading both should work according to standards, maybe full URLs fail with some weird proxy configurations. The relative URLs do make a bit more sense and it seems the [examples](https://docs.python.org/3/library/http.client.html#examples) in Python's documentation favor that as well. I'll change it.

**Comment by rinigus** [comment]
Thank you!
