### ISSUE TITLE
Add support for heading by routers

### ISSUE THREAD

**Issue by rinigus** [otsaloma/poor-maps#44]
When calculating a route, its sometimes advantageous to take into account current motion direction. In particular, its important for re-routing while driving. Mapzen/Valhalla have `heading` option for it, maybe other as well.

**Comment by rinigus** [comment]
This is addressed in 32e9a53600dc4506caca9a12b07cfd4a8297fe45 (despite comment referring to another issue)

**Comment by otsaloma** [comment]
Thanks, this makes sense. I'll look into how other routers handle this before fixing the router API.

**Comment by rinigus** [comment]
Sure. I skimmed a bit the other routers, but haven't done proper research on it.

**Comment by otsaloma** [comment]
Looked into it, didn't learn much, I think it's OK.

**Comment by otsaloma** [comment]
I'll close this already as it's coming up in that PR.
