### ISSUE TITLE
Translations broken in Sailfish 2.1.1.24

### ISSUE THREAD

**Issue by ghost** [otsaloma/poor-maps#48]
Poor Maps stays in English regardless of the system language.

**Comment by otsaloma** [comment]
I have no control over how sailfish-qml loads QML translations. This is most likely a bug in SFOS, not even in a stable release, it's reported at TJC, let's just wait for the final 2.1.1.

**Comment by ghost** [comment]
Do you have a link to the post on TJC? I can't find it.

**Comment by otsaloma** [comment]
https://together.jolla.com/question/164349/release-notes-211-jamsanjoki/?answer=164564#post-id-164564

**Comment by otsaloma** [comment]
Seems to be fixed in 2.1.1.26.
