### ISSUE TITLE
Auto-center and auto-rotate don't work in v0.32

### ISSUE THREAD

**Issue by carmenfdezb** [otsaloma/poor-maps#51]
I've enabled both options but don't work

**Comment by otsaloma** [comment]
Cannot reproduce, works for me.

**Comment by carmenfdezb** [comment]
Sorry, maybe it works, but the options switch when I start the navigation.
In other words, if I enable auto-center and auto-rotate, and I start the navigation, both options are disabled.

**Comment by otsaloma** [comment]
Still can't reproduce.

Are you sure you're starting the navigation? The leftmost button in the navigation page is now a combined begin/pause/resume button (similar to play/pause in media players). If you already started navigation, the button will be a pause button and will disable auto-center and auto-rotate.

**Comment by carmenfdezb** [comment]
Ok, you are right, if I push on pause button it disables auto-center and auto-rotate. I didn't notice this until now, sorry.
