### ISSUE TITLE
Can we support @3x tiles?

### ISSUE THREAD

**Issue by otsaloma** [otsaloma/poor-maps#53]
That would be 768x768 pixels as per the old standards and as per what tileserver-gl returns.

**Comment by klokan** [comment]
It is supported by our Tileserver-GL...

**Comment by otsaloma** [comment]
Yes, thanks, I have just set up a Tileserver GL instance. That together with the upcoming Sailfish X screen specs led to this issue, which meant adding support for scales not powers of two to the client map view. To answer the issue title, yes, we now have support for `@3x`.
