### ISSUE TITLE
OSM POI list when searching for nearby venues

### ISSUE THREAD

**Issue by aquac** [otsaloma/poor-maps#54]
When using the "search nearby" feature from the map, I am often facing the problem that I don't know the correct OSM POI type to enter there. E.g. today I was looking for DIY stores but didn't know that they are actually mostly listed under "hardware" rather than "doityourself".

I there would like to propose to have (in the search nearby feature and when selecting OSM as search provider) a list of POI groups and names. To me e.g. the listing provided in http://openpoimap.org/ is very useful.

**Comment by otsaloma** [comment]
I understand the problem, but it's not really practical for me to work around it. Just look at the length of the following list. And despite the long list, my favorite example, grocery store, still can't be found.

http://wiki.openstreetmap.org/wiki/Nominatim/Special_Phrases/EN

This is something that should be handled on the server side and OSM data and Nominatim are just really bad at this.

Is there a reason why you aren't using the Foursquare provider? Foursquare specifically has solved the problem you're seeing and their data is mostly better than OSM.
