### ISSUE TITLE
Implementing train routing with stop points

### ISSUE THREAD

**Issue by bonanza123** [otsaloma/poor-maps#56]
I'm currently trying to implement some train routing providers which unfortunately do not provide journey planning from position data but instead only from fixed stop points.
Therefore, I added a gecoder with returns (besides `title`, `description`, `x` and `y`) an `id` which is a ID of the stop point.
Because the journey planning requires knowledge of the startId and destinationId, the `route` implementation would require (instead of `x` and `y`) the `id`. Would it be possible to pass this information also (or instead of) the `x` and `y` data to `route`?

**Comment by otsaloma** [comment]
What do you mean? The `route` function takes arguments `fm` and `to` that can be either coordinates or strings. Those strings could well be stop names or IDs.

Secondly, where do you do your geocoding? You should probably be doing it under your route function implementation and pass the result to the journey planner API, there should be nothing between that.

```python
def route(fm, to, heading, params):
    geocoder = poor.Geocoder("xxx")
    fm = geocoder.geocode(fm)[0]["id"]
    to = geocoder.geocode(to)[0]["id"]
    url = ...
    result = poor.http.get_json(url)
    ...
```
