### ISSUE TITLE
rpm failed to install on sailfish os 2.1.2.3

### ISSUE THREAD

**Issue by mschaaf** [otsaloma/poor-maps#57]
I only get installation failed without any detailed error message.
I downloaded the rpm from github.

**Comment by otsaloma** [comment]
I can't reproduce this.

It would help if you can try installation from the command line in developer mode with `pkcon install-local`. That might give some output. Also, try `pkcon refresh` before installing to update the repos.

https://sailfishos.org/wiki/Sailfish_OS_Cheat_Sheet#Package_Handling

**Comment by mschaaf** [comment]
It fails with dependency qt5-plugin-geoservices-here is missing
But running the installation after pkcon refresh with pkcon install-local installed poor-maps
Thank you for your help
