### ISSUE TITLE
No results when GPS isn’t available yet.

### ISSUE THREAD

**Issue by Profpatsch** [otsaloma/poor-maps#6]
When you do a search from (or to) current location and the GPS is not yet ready, it returns “No results”.

I recommend to check for this first and display a spinning wheel or similar with the title “Waiting for location services to activate”.

**Comment by otsaloma** [comment]
Is this with AGPS off? Jolla phone or some other device?

On the Jolla phone, with AGPS I always have some crude positioning, so I've never paid attention. There might be other functionality as well that assumes positioning is ready -- I'll need to look through that.

**Comment by otsaloma** [comment]
If positioning data not yet available
- Share current position in the main menu shows a spinner and ignores tapping
- Navigation page from and to fields show a spinner and prevent advancing
- Nearby page near field shows a spinner and prevents advancing

So, no textual explanations, but I assume people who turn AGPS off understand what they're doing, run into this all the time, and will understand subtle hints.

![no-gps-1](https://cloud.githubusercontent.com/assets/237265/12077523/87f8776a-b1f0-11e5-9760-1deabe0c8cb2.png)

![no-gps-2](https://cloud.githubusercontent.com/assets/237265/12077525/8cf62a50-b1f0-11e5-889c-8ef46cf6e02c.png)

![no-gps-3](https://cloud.githubusercontent.com/assets/237265/12077526/92adfb9e-b1f0-11e5-86b3-fc9171d5b398.png)

**Comment by Profpatsch** [comment]
Nice, thanks!

Is AGPS location via wifi access point location database?

**Comment by otsaloma** [comment]
> Is AGPS location via wifi access point location database?

At least on the Jolla phone, AGPS uses "HERE services". I don't know if it's specified anywhere what that means, but by my experience it uses both wifi access point location database (probably only if wifi is on?) and cell towers.

And, in general, Poor Maps uses Qt Positioning, which uses whatever positioning sources that OS or device makers configure it to use.
