### ISSUE TITLE
Maneuver preview doesn't rotate map

### ISSUE THREAD

**Issue by Thra11** [otsaloma/poor-maps#60]
For example:
1. Enter a destination roughly South of your current position. Start following the route.
2. Turn on auto-rotate. North should now be at the bottom of the map.
3. Tap the routing panel at the top of the screen, then swipe left to view the list of maneuvers.
4. Touch an upcoming maneuvre. The map zooms in and centres on the maneuver. However, it doesn't rotate the map, so North is now at the top. It is easy for the user to mistakenly think that they will be approaching the junction from the bottom of the screen, but they will in fact be coming from the top of the screen.

Ideally, I think we should rotate the map to align to the route trace so that the 'incoming' side of the route enters the screen from the bottom in an upward direction. That way, the map is oriented the same way as it will be when the user actually gets to it.

Adding direction arrows to the route trace could also help to avoid confusion in this and possibly other situations, but I don't know if that's feasible.

**Comment by otsaloma** [comment]
Yes, ideally the map should be rotated, but this is very low-priority.
