### ISSUE TITLE
Poor-maps not ship spanish translation on Bolivia-Spanish

### ISSUE THREAD

**Issue by ghost** [otsaloma/poor-maps#64]
Lapuanjoki It is already to everyone, so poor-maps and same to poor-maps-GL spanish not work. Modrana does, as example.
Thanks

**Comment by otsaloma** [comment]
As I already replied on OpenRepos, but received no answer:

> The Spanish in Poor Maps is es_ES, i.e. Spanish Spanish. Should it be plain es instead?

I simply cannot know the depth of differences between different Spanishes and need in translation issues more than "not work" if I am to override decisions of translators, which in general I don't like to do. You can also contact the [translator in question](https://www.transifex.com/user/profile/carmenfdezb/).

**Comment by ghost** [comment]
Well;  es_ES **is** spanish_Spain **not** spanish_SPANISH as an example. perhaps if you clone the file es_ES **to** es_BL(if i correct) may be work. `

**Comment by otsaloma** [comment]
Spanish Spanish as in Bolivian Spanish! And, yes, the file can be copied, but that would effectively be the same as having a single "es.po" file. That's what I'm asking – is the current "es_ES" linguistically OK to be considered common Spanish, that all from Bolivia to Equatorial Guinea would use when a country-specific translation is not found?

**Comment by ghost** [comment]
Yes absolute, Spanish is **Spanish-Everywhere**

**Comment by ghost** [comment]
Also otsaloma can you explain me on poor-maps and whogo-maps?
Thanks

**Comment by otsaloma** [comment]
Done now, on Transifex too.

WhoGo Maps is coming soon, more on that then.
