### ISSUE TITLE
Error message from API calls not passed to QML

### ISSUE THREAD

**Issue by Olf0** [otsaloma/poor-maps#65]
Two days ago I wondered, why routing did not work anymore.  Starting Poor Maps via `sailfish-qml harbour-poor-maps` ([thanks](https://talk.maemo.org/showthread.php?p=1542202#post1542202)) revealed, that the selected navigation service (in this case the default: Mapzen) was unreachable.  Selecting MapQuest restored Poor Maps' routing capabilities immediately.

As in such cases, routing just doesn't work, IMO there should be an error message.
Presumably this issue affects [WhoGo Maps](https://github.com/otsaloma/whogo-maps/issues), too.

Tested with Poor Maps 0.34.2 und SFOS 2.1.4.14 on a Jolla 1 phone.
Sorry, I missed to record the debug output the day before yesterday and currently all online navigation services Poor Maps offers are working well.

**Comment by otsaloma** [comment]
I'm going to make a release that removes Mapzen's geocoder and router. Error messages would be nice yes, but are difficult as they require some manually inserted non-trivial glue. Currently only timeouts relay error messages.

**Comment by Olf0** [comment]
IMHO there are a couple of QML apps for SFOS to "steal" code from, which either display a regular notification or a special single line notification on black background, e.g. [Storeman](https://github.com/mentaljam/harbour-storeman) (which does both).
