### ISSUE TITLE
Mapzen requests fail

### ISSUE THREAD

**Issue by Olf0** [otsaloma/poor-maps#67]
When using Mapzen as online navigation provider, `sailfish-qml harbour-poor-maps` shows:
    
    GET https://search.mapzen.com/v1/search?api_key=search--jugOXM&text=Cologne&size=1
    Establishing connection to search.mapzen.com
    GET failed: SSLError: [SSL: SSLV3_ALERT_HANDSHAKE_FAILURE] sslv3 alert handshake failure (_ssl.c:600)

* Full log section: [poor-maps_mapzen-ssl.txt](https://github.com/otsaloma/poor-maps/files/1831211/poor-maps_mapzen-ssl.txt)
* Full log: [poor-maps_mapzen-ssl.log.txt](https://github.com/otsaloma/poor-maps/files/1831253/poor-maps_mapzen-ssl.log.txt)

Presumably this issue affects [WhoGo Maps](https://github.com/otsaloma/whogo-maps/issues), too.
Side note: Issue #65 is somewhat related, but different.

Tested with Poor Maps 0.34.2 und SFOS 2.1.4.14 on a Jolla 1 phone.

**Comment by otsaloma** [comment]
Yes, they shut down, I'll remove.

**Comment by Olf0** [comment]
Ah, I see: [Mapzen is shutting down its services.](https://mapzen.com/blog/shutdown/)
