### ISSUE TITLE
Warnings in console output

### ISSUE THREAD

**Issue by Olf0** [otsaloma/poor-maps#68]
While Poor Maps just writes a couple of warnings to StdErr when started simply displaying a Map, it outputs a many warnings when started in navigation mode.

* Startup output, when just displaying a Map:

      [D] unknown:0 - Using Wayland-EGL
      [D] unknown:0 - Got library name:  "/usr/lib/qt5/qml/io/thp/pyotherside/libpyothersideplugin.so"
      [D] unknown:0 - No proxy parameter specified.
      [W] unknown:0 - Failed to read HERE map version.
      [D] onCompleted:334 - Warning: specifying an object instance for initialPage is sub-optimal - prefer to use a Component
      [D] unknown:0 - "Unexpected reply signature: got \"\", expected \"a{sv}\""
  Only the last line looks a bit strange to me.
  Note, that I do not have Here Maps installed.
* When closing Poor Maps, it always outputs:

      [W] unknown:0 - Unable to write tile cache file  "/dev/null/queue1"
      [W] unknown:0 - Unable to write tile cache file  "/dev/null/queue2"
      [W] unknown:0 - Unable to write tile cache file  "/dev/null/queue3"
      [W] unknown:0 - Unable to write tile cache file  "/dev/null/queue4"
   On first sight this looks like a tiny mishap / oversight.
* But when Poor Maps is shut down in navigation mode and restarted thereafter, it produces a somewhat more worrying warnings (while working properly!): [poor-maps.log3.txt](https://github.com/otsaloma/poor-maps/files/1831465/poor-maps_mapzen-ssl.log3.txt)
    These debug and warning messages pile up when using Poor Maps, for above log file I closed Poor Maps ~ 10 seconds after it opened.  Actually I saw quite a lot more warnings and even some errors on a simple "Open --> Close"-cycle, when I started testing a few hours ago, but cannot reproduce that anymore.

**Comment by otsaloma** [comment]
This is normal.
