### ISSUE TITLE
TTS is not working stable

### ISSUE THREAD

**Issue by Olf0** [otsaloma/poor-maps#69]
Although Poor Maps states "Voice navigation on", when hitting "Begin ▷"-button, it ever failed to generate spoken navigation instructions on one Jolla 1 phone and ceased to do so after a few days on my other.
When having a route preselected and just starting the navigation after opening Poor Maps, only [one other message appears (three consecutive times)](https://github.com/otsaloma/poor-maps/files/1831573/poor-maps.log4.txt) compared to [without starting the navigation](https://github.com/otsaloma/poor-maps/files/1831465/poor-maps_mapzen-ssl.log3.txt): `TypeError: Cannot read property of null`
I once managed to see a couple of successful calls of `pico2wave` followed by a many (~ 10) lines of Python errors (Poor Maps was still silent then), but I cannot reproduce this.  But since I started testing (this issue is, what I am really after), outputting nothing obviously related to TTS was Poor Maps' regular behaviour, even though it always stated "Voice navigation on", when starting a navigation.

I will keep on trying, if I can make Poor Maps at least call pico2wave once more.  Any ideas what else to try before simply un- and reinstalling the Poor Maps and PicoTTS RPMs?

Tested with Poor Maps 0.34.2 und SFOS 2.1.4.14 on two Jolla 1 phones, `pico2wave` is working properly at the command line (producing correct WAV files).

**Comment by Olf0** [comment]
Missed to note, that I checked the media volume being at ~ 80%, the Poor Maps' settings "Show navigation instructions" and "Voice navigation instructions" in the navigation pages, plus toggled the setting "Voice gender" in its Preferences page many times.

**Comment by otsaloma** [comment]
Normally, Poor Maps, should print the command and return value as the navigation instructions are generated to audio files. If you don't see this output, then they're not being generated. There should also be an error message below the command if it tries but fails.

    espeak --stdout -v english-us hello 0

Also, try changing your console encoding as I believe it's ASCII by default. I tried to avoid problems with that, but some might remain.

    $ export LANG=en_US.UTF-8
    $ export LANGUAGE=en_US.UTF-8
    $ export LC_ALL=en_US.UTF-8
    $ locale
    $ sailfish-qml harbour-poor-maps

**Comment by Olf0** [comment]
I played with TTS a bit more and still have nothing substantial, but a few more observations:

* When hitting "Reroute" a couple of times (typically 3), suddenly Poor Maps / WhoGo Maps start to speak, although just the two phrases "Diversion" and "New route found" (sometimes both, sometimes just one of them), in the language selected in Poor / WhoGo Maps.
* When it fails to use TTS it shows "Voice navigation instructions" dimmed (which supposedly means "on, but not able to toggle", but that does not make any sense AFAICS): ![screenshot_20180402_003](https://user-images.githubusercontent.com/16547876/38179520-aa072cba-3624-11e8-93ec-49fc43b3a745.png)
* This setting "Voice navigation instructions" becomes fully lit (i.e. "on"), without being touched, when triggering "Reroute" a couple of times!
* When TTS is working, I sure see the calls to picotts in the command line output.  Actually a couple of other WAV files are prepared in /tmp, far more than the two triggered by rerouting (see first bullet point above).
* Poor Maps and WhoGo Maps exhibit exactly the same behaviour.

Tested with Poor Maps 0.34.2 and WhoGo Maps 0.92 on a Jolla 1 phone under SailfishOS 2.1.4.14, using picotts and German language voice.
Note that seemingly one has to select the female voice in Poor Maps / WhoGo Maps for voice navigation in German, as picotts apparently only offers a female German language voice.

**Comment by Olf0** [comment]
BTW, `env | grep "^L.*"` provides `LANG=en_GB.utf8` (`LANGUAGE` and `LC_ALL` are unset), but I do want to have the choice between an English (any) voice and a German one at the GUI, while leaving LANG and locale at `en_GB` (in lack of `en_DK` "European English" in SFOS).

Actually this aspect seems to work well: When Poor / WhoGo Maps narrates navigation instructions successfully, they always were "spoken" in the language selected in its GUI.

**Comment by Olf0** [comment]
BTW (found out yesterday), stubbornly hitting "Reroute" actually lets the first navigation instruction being narrated about every fourth to fifth time Poor / WhoGo Maps states "Diversion" and / or  "New route found", hence it usually takes more than 10 tries (hitting "Reroute") to let a voice navigation start successfully.  Rarely (only seen / heard with Poor Maps yet), the voice navigation commands are narrated right away, without a prepended  "Diversion" and / or  "New route found", although "New route found" is always displayed (i.e. visually).

This behaviour is consistent (now) across two Jolla 1 phones, on both under Poor Maps *and* WhoGo Maps.

P.S. / edit: The routing engine used seems to be irrelevant (tried Valhalla, libosmscout and online), at least for this fundamental behaviour.

**Comment by Olf0** [comment]
BTW, [brvmd](https://talk.maemo.org/showpost.php?p=1544076&postcount=124) and pichlo (also in that WhoGo TMO thread) seem to experience exactly the same behaviour in WhoGo Maps / Poor Maps, although they use *mimic* instead of *picotts*.

Unfortunately, this issue renders (the basically working) voice navigation useless since its inception.
