### ISSUE TITLE
offline mode 

### ISSUE THREAD

**Issue by lewadedun** [otsaloma/poor-maps#7]
is this possible?

**Comment by otsaloma** [comment]
> is this possible?

Much in this world is possible, including offline maps.

But, in short, I think it's a lot of work, it's not something I want to do, and I'd rather see offline maps as a separate shared component.

See a recent thread at TMO, quote from Martin Kolman below and my response.

> Or maybe rather than doing another monolitic navigation up the functionality provided by the project (offline routing, offline map rendering, offline address search, etc.) could be split to postable & language agnostic modules/daemons/utilities that existing and future navigation systems (such as modRana and Poor Maps) could make use of ?

http://talk.maemo.org/showthread.php?t=96090

**Comment by otsaloma** [comment]
I'll close this as out of scope. Please open a new issue if a shared offline component emerges that we could use.
